#!/bin/bash
dir=$(dirname "$0")
chown root:wheel /Applications/iXameXuardian.app/xx_daemon
chmod 6755 /Applications/iXameXuardian.app/xx_daemon

cp /Applications/iXameXuardian.app/xqua.xx.*.plist /Library/LaunchDaemons/
launchctl load -w /Library/LaunchDaemons/xqua.xx.daemon.plist

if [[ ! -d /var/mobile/Library/iXameXuardian ]]; then
    mkdir /var/mobile/Library/iXameXuardian
    chown mobile /var/mobile/Library/iXameXuardian
fi



uicache

exit 0

