#!/bin/bash

launchctl unload -w /Library/LaunchDaemons/aqua.gg.daemon.plist

rm /Library/LaunchDaemons/aqua.gg.*.plist

if [[ -d /var/mobile/Library/iXameXuardian ]]; then
    rm -rf /var/mobile/Library/iXameXuardian
fi

if [[ -d /Applications/iXameXuardian.app ]]; then
    rm -rf /Applications/iXameXuardian.app
fi

uicache

exit 0
